[package]
name = "neurosay"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.11.27", features = [
    "json",
    "deflate",
    "gzip",
    "blocking",
] }
serde = { version = "1.0.197", features = ["derive"] }
textwrap = "0.16.1"
